# backend/config/log_config.yaml
default_level: "INFO"
format_type: "json"
text_format: "[%(asctime)s] %(name)s:%(levelname)s - %(message)s"
json_format:
  asctime: "%(asctime)s"
  levelname: "%(levelname)s"
  name: "%(name)s"
  message: "%(message)s"
filename: "./backend/logs/app.log"
max_bytes: 10485760
backup_count: 5
development:
  level: "DEBUG"
  console: true
  console_format_type: "text_color"
production:
  level: "INFO"
  console: false